version: "3.9"

services:
  backend:
    image: mood-today-back
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"

  frontend:
    image: mood-today-front
    build:
      context: ./frontend
    ports:
      - "9999:80"
    depends_on:
      - backend
