version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "90:90"
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    
  backend:
    image: mood-today-back
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      HOST: ${HOST}
      PORT: ${PORT}
    # ports:
    #   - "${PORT}:${PORT}"   # внешний порт совпадает с внутренним
    networks:
      - app-network

  frontend:
    image: mood-today-front
    build:
      context: ./frontend
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      PORT: ${FRONTEND_PORT}
      HOST: ${FRONTEND_HOST}
    # ports:
    #   - "9999:80"   # внешний порт для доступа через IP
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
