version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - backend
      - frontend
    container_name: nginx_proxy
    restart: always
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      HOST: 0.0.0.0
      PORT: 8000
    networks:
      - dev

networks:
  dev:
    driver: bridge
