version: "3.9"

services:
  nginx:
    build:
      context: ./frontend
    container_name: nginx_proxy
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      HOST: 0.0.0.0
      PORT: 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
